/**
 * EIP-6963: Multi Injected Provider Discovery.
 *
 * Modern browser-extension wallets announce themselves via an
 * `eip6963:announceProvider` event in response to an `eip6963:requestProvider`
 * dispatch. This lets a dapp see every installed wallet by name and icon
 * rather than fighting over `window.ethereum`.
 *
 * Spec: https://eips.ethereum.org/EIPS/eip-6963
 */

export interface Eip6963ProviderInfo {
  /** UUID v4 generated by the wallet for this announcement. Changes per page load. */
  uuid: string;
  /** Display name, e.g. "MetaMask", "Rabby Wallet", "Brave Wallet". */
  name: string;
  /** Data URL of the wallet's icon (typically SVG). */
  icon: string;
  /** Reverse-DNS identifier, e.g. "io.metamask", "io.rabby". Stable across versions. */
  rdns: string;
}

/**
 * The structural shape of a wallet provider we care about. Matches
 * window.ethereum well enough for ethers' BrowserProvider and for the
 * EIP-1193 event emitter methods we use.
 */
export interface Eip1193Provider {
  request: (args: { method: string; params?: unknown[] }) => Promise<unknown>;
  on: (event: string, handler: (...args: unknown[]) => void) => void;
  removeListener: (event: string, handler: (...args: unknown[]) => void) => void;
}

export interface Eip6963ProviderDetail {
  info: Eip6963ProviderInfo;
  provider: Eip1193Provider;
}

interface AnnounceEvent extends Event {
  detail: Eip6963ProviderDetail;
}

/**
 * Subscribe to provider announcements and immediately request any that are
 * already injected. Calls `onDetail` for every distinct wallet (deduplicated
 * by rdns). Returns an unsubscribe function.
 */
export function listenForProviders(onDetail: (detail: Eip6963ProviderDetail) => void): () => void {
  if (typeof window === 'undefined') return () => {};

  const seen = new Set<string>();
  const handler = (event: Event) => {
    const detail = (event as AnnounceEvent).detail;
    if (!detail?.info?.rdns) return;
    if (seen.has(detail.info.rdns)) return;
    seen.add(detail.info.rdns);
    onDetail(detail);
  };

  window.addEventListener('eip6963:announceProvider', handler);
  // Ask wallets that loaded before us to re-announce themselves.
  window.dispatchEvent(new Event('eip6963:requestProvider'));

  return () => window.removeEventListener('eip6963:announceProvider', handler);
}
